#include <interception_macros.h>

namespace app::methods::PlayFab::PlayFabGroupsAPI {
IL2CPP_REGISTER_METHOD(0x002FA000, void, __cctor, ());
IL2CPP_REGISTER_METHOD(0x01A2A140, void, ForgetAllCredentials, ());
IL2CPP_REGISTER_METHOD(0x01A2A1D0, void, AcceptGroupApplication, (AcceptGroupApplicationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A2E0, void, AcceptGroupInvitation, (AcceptGroupInvitationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A3F0, void, AddMembers, (AddMembersRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A500, void, ApplyToGroup, (ApplyToGroupRequest * request, Action_1_PlayFab_GroupsModels_ApplyToGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A610, void, BlockEntity, (BlockEntityRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A720, void, ChangeMemberRole, (ChangeMemberRoleRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A830, void, CreateGroup, (CreateGroupRequest * request, Action_1_PlayFab_GroupsModels_CreateGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2A940, void, CreateRole, (CreateGroupRoleRequest * request, Action_1_PlayFab_GroupsModels_CreateGroupRoleResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2AA50, void, DeleteGroup, (DeleteGroupRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2AB60, void, DeleteRole, (DeleteRoleRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2AC70, void, GetGroup, (GetGroupRequest * request, Action_1_PlayFab_GroupsModels_GetGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2AD80, void, InviteToGroup, (InviteToGroupRequest * request, Action_1_PlayFab_GroupsModels_InviteToGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2AE90, void, IsMember, (IsMemberRequest * request, Action_1_PlayFab_GroupsModels_IsMemberResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2AFA0, void, ListGroupApplications, (ListGroupApplicationsRequest * request, Action_1_PlayFab_GroupsModels_ListGroupApplicationsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B0B0, void, ListGroupBlocks, (ListGroupBlocksRequest * request, Action_1_PlayFab_GroupsModels_ListGroupBlocksResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B1C0, void, ListGroupInvitations, (ListGroupInvitationsRequest * request, Action_1_PlayFab_GroupsModels_ListGroupInvitationsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B2D0, void, ListGroupMembers, (ListGroupMembersRequest * request, Action_1_PlayFab_GroupsModels_ListGroupMembersResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B3E0, void, ListMembership, (ListMembershipRequest * request, Action_1_PlayFab_GroupsModels_ListMembershipResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B4F0, void, ListMembershipOpportunities, (ListMembershipOpportunitiesRequest * request, Action_1_PlayFab_GroupsModels_ListMembershipOpportunitiesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B600, void, RemoveGroupApplication, (RemoveGroupApplicationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B710, void, RemoveGroupInvitation, (RemoveGroupInvitationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B820, void, RemoveMembers, (RemoveMembersRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2B930, void, UnblockEntity, (UnblockEntityRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2BA40, void, UpdateGroup, (UpdateGroupRequest * request, Action_1_PlayFab_GroupsModels_UpdateGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2BB50, void, UpdateRole, (UpdateGroupRoleRequest * request, Action_1_PlayFab_GroupsModels_UpdateGroupRoleResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
}
