#include <interception_macros.h>

namespace app::methods::PlayFab::PlayFabGroupsInstanceAPI {
IL2CPP_REGISTER_METHOD(0x002FA000, void, __ctor, (PlayFabGroupsInstanceAPI * __this));
IL2CPP_REGISTER_METHOD(0x002FA490, void, __ctor, (PlayFabGroupsInstanceAPI * __this, PlayFabApiSettings * settings));
IL2CPP_REGISTER_METHOD(0x002FB940, void, __ctor, (PlayFabGroupsInstanceAPI * __this, PlayFabAuthenticationContext * context));
IL2CPP_REGISTER_METHOD(0x0058DA40, void, __ctor, (PlayFabGroupsInstanceAPI * __this, PlayFabApiSettings * settings, PlayFabAuthenticationContext * context));
IL2CPP_REGISTER_METHOD(0x002FB940, void, SetAuthenticationContext, (PlayFabGroupsInstanceAPI * __this, PlayFabAuthenticationContext * context));
IL2CPP_REGISTER_METHOD(0x002FB930, PlayFabAuthenticationContext *, GetAuthenticationContext, (PlayFabGroupsInstanceAPI * __this));
IL2CPP_REGISTER_METHOD(0x017B4520, void, ForgetAllCredentials, (PlayFabGroupsInstanceAPI * __this));
IL2CPP_REGISTER_METHOD(0x01A2BC60, void, AcceptGroupApplication, (PlayFabGroupsInstanceAPI * __this, AcceptGroupApplicationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2BD80, void, AcceptGroupInvitation, (PlayFabGroupsInstanceAPI * __this, AcceptGroupInvitationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2BEA0, void, AddMembers, (PlayFabGroupsInstanceAPI * __this, AddMembersRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2BFC0, void, ApplyToGroup, (PlayFabGroupsInstanceAPI * __this, ApplyToGroupRequest * request, Action_1_PlayFab_GroupsModels_ApplyToGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C0E0, void, BlockEntity, (PlayFabGroupsInstanceAPI * __this, BlockEntityRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C200, void, ChangeMemberRole, (PlayFabGroupsInstanceAPI * __this, ChangeMemberRoleRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C320, void, CreateGroup, (PlayFabGroupsInstanceAPI * __this, CreateGroupRequest * request, Action_1_PlayFab_GroupsModels_CreateGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C440, void, CreateRole, (PlayFabGroupsInstanceAPI * __this, CreateGroupRoleRequest * request, Action_1_PlayFab_GroupsModels_CreateGroupRoleResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C560, void, DeleteGroup, (PlayFabGroupsInstanceAPI * __this, DeleteGroupRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C680, void, DeleteRole, (PlayFabGroupsInstanceAPI * __this, DeleteRoleRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C7A0, void, GetGroup, (PlayFabGroupsInstanceAPI * __this, GetGroupRequest * request, Action_1_PlayFab_GroupsModels_GetGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C8C0, void, InviteToGroup, (PlayFabGroupsInstanceAPI * __this, InviteToGroupRequest * request, Action_1_PlayFab_GroupsModels_InviteToGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2C9E0, void, IsMember, (PlayFabGroupsInstanceAPI * __this, IsMemberRequest * request, Action_1_PlayFab_GroupsModels_IsMemberResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2CB00, void, ListGroupApplications, (PlayFabGroupsInstanceAPI * __this, ListGroupApplicationsRequest * request, Action_1_PlayFab_GroupsModels_ListGroupApplicationsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2CC20, void, ListGroupBlocks, (PlayFabGroupsInstanceAPI * __this, ListGroupBlocksRequest * request, Action_1_PlayFab_GroupsModels_ListGroupBlocksResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2CD40, void, ListGroupInvitations, (PlayFabGroupsInstanceAPI * __this, ListGroupInvitationsRequest * request, Action_1_PlayFab_GroupsModels_ListGroupInvitationsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2CE60, void, ListGroupMembers, (PlayFabGroupsInstanceAPI * __this, ListGroupMembersRequest * request, Action_1_PlayFab_GroupsModels_ListGroupMembersResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2CF80, void, ListMembership, (PlayFabGroupsInstanceAPI * __this, ListMembershipRequest * request, Action_1_PlayFab_GroupsModels_ListMembershipResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D0A0, void, ListMembershipOpportunities, (PlayFabGroupsInstanceAPI * __this, ListMembershipOpportunitiesRequest * request, Action_1_PlayFab_GroupsModels_ListMembershipOpportunitiesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D1C0, void, RemoveGroupApplication, (PlayFabGroupsInstanceAPI * __this, RemoveGroupApplicationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D2E0, void, RemoveGroupInvitation, (PlayFabGroupsInstanceAPI * __this, RemoveGroupInvitationRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D400, void, RemoveMembers, (PlayFabGroupsInstanceAPI * __this, RemoveMembersRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D520, void, UnblockEntity, (PlayFabGroupsInstanceAPI * __this, UnblockEntityRequest * request, Action_1_PlayFab_GroupsModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D640, void, UpdateGroup, (PlayFabGroupsInstanceAPI * __this, UpdateGroupRequest * request, Action_1_PlayFab_GroupsModels_UpdateGroupResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2D760, void, UpdateRole, (PlayFabGroupsInstanceAPI * __this, UpdateGroupRoleRequest * request, Action_1_PlayFab_GroupsModels_UpdateGroupRoleResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
}
