#include <interception_macros.h>

namespace app::methods::PlayFab::PlayFabMultiplayerAPI {
IL2CPP_REGISTER_METHOD(0x002FA000, void, __cctor, ());
IL2CPP_REGISTER_METHOD(0x01A2E6C0, void, ForgetAllCredentials, ());
IL2CPP_REGISTER_METHOD(0x01A2E750, void, CancelAllMatchmakingTicketsForPlayer, (CancelAllMatchmakingTicketsForPlayerRequest * request, Action_1_PlayFab_MultiplayerModels_CancelAllMatchmakingTicketsForPlayerResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2E860, void, CancelMatchmakingTicket, (CancelMatchmakingTicketRequest * request, Action_1_PlayFab_MultiplayerModels_CancelMatchmakingTicketResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2E970, void, CreateBuildWithCustomContainer, (CreateBuildWithCustomContainerRequest * request, Action_1_PlayFab_MultiplayerModels_CreateBuildWithCustomContainerResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2EA80, void, CreateBuildWithManagedContainer, (CreateBuildWithManagedContainerRequest * request, Action_1_PlayFab_MultiplayerModels_CreateBuildWithManagedContainerResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2EB90, void, CreateMatchmakingTicket, (CreateMatchmakingTicketRequest * request, Action_1_PlayFab_MultiplayerModels_CreateMatchmakingTicketResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2ECA0, void, CreateRemoteUser, (CreateRemoteUserRequest * request, Action_1_PlayFab_MultiplayerModels_CreateRemoteUserResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2EDB0, void, CreateServerMatchmakingTicket, (CreateServerMatchmakingTicketRequest * request, Action_1_PlayFab_MultiplayerModels_CreateMatchmakingTicketResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2EEC0, void, DeleteAsset, (DeleteAssetRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2EFD0, void, DeleteBuild, (DeleteBuildRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F0E0, void, DeleteCertificate, (DeleteCertificateRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F1F0, void, DeleteRemoteUser, (DeleteRemoteUserRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F300, void, EnableMultiplayerServersForTitle, (EnableMultiplayerServersForTitleRequest * request, Action_1_PlayFab_MultiplayerModels_EnableMultiplayerServersForTitleResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F410, void, GetAssetUploadUrl, (GetAssetUploadUrlRequest * request, Action_1_PlayFab_MultiplayerModels_GetAssetUploadUrlResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F520, void, GetBuild, (GetBuildRequest * request, Action_1_PlayFab_MultiplayerModels_GetBuildResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F630, void, GetContainerRegistryCredentials, (GetContainerRegistryCredentialsRequest * request, Action_1_PlayFab_MultiplayerModels_GetContainerRegistryCredentialsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F740, void, GetMatch, (GetMatchRequest * request, Action_1_PlayFab_MultiplayerModels_GetMatchResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F850, void, GetMatchmakingQueue, (GetMatchmakingQueueRequest * request, Action_1_PlayFab_MultiplayerModels_GetMatchmakingQueueResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2F960, void, GetMatchmakingTicket, (GetMatchmakingTicketRequest * request, Action_1_PlayFab_MultiplayerModels_GetMatchmakingTicketResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2FA70, void, GetMultiplayerServerDetails, (GetMultiplayerServerDetailsRequest * request, Action_1_PlayFab_MultiplayerModels_GetMultiplayerServerDetailsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2FB80, void, GetQueueStatistics, (GetQueueStatisticsRequest * request, Action_1_PlayFab_MultiplayerModels_GetQueueStatisticsResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2FC90, void, GetRemoteLoginEndpoint, (GetRemoteLoginEndpointRequest * request, Action_1_PlayFab_MultiplayerModels_GetRemoteLoginEndpointResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2FDA0, void, GetTitleEnabledForMultiplayerServersStatus, (GetTitleEnabledForMultiplayerServersStatusRequest * request, Action_1_PlayFab_MultiplayerModels_GetTitleEnabledForMultiplayerServersStatusResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2FEB0, void, JoinMatchmakingTicket, (JoinMatchmakingTicketRequest * request, Action_1_PlayFab_MultiplayerModels_JoinMatchmakingTicketResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A2FFC0, void, ListArchivedMultiplayerServers, (ListMultiplayerServersRequest * request, Action_1_PlayFab_MultiplayerModels_ListMultiplayerServersResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A300D0, void, ListAssetSummaries, (ListAssetSummariesRequest * request, Action_1_PlayFab_MultiplayerModels_ListAssetSummariesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A301E0, void, ListBuildSummaries, (ListBuildSummariesRequest * request, Action_1_PlayFab_MultiplayerModels_ListBuildSummariesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A302F0, void, ListCertificateSummaries, (ListCertificateSummariesRequest * request, Action_1_PlayFab_MultiplayerModels_ListCertificateSummariesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30400, void, ListContainerImages, (ListContainerImagesRequest * request, Action_1_PlayFab_MultiplayerModels_ListContainerImagesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30510, void, ListContainerImageTags, (ListContainerImageTagsRequest * request, Action_1_PlayFab_MultiplayerModels_ListContainerImageTagsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30620, void, ListMatchmakingQueues, (ListMatchmakingQueuesRequest * request, Action_1_PlayFab_MultiplayerModels_ListMatchmakingQueuesResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30730, void, ListMatchmakingTicketsForPlayer, (ListMatchmakingTicketsForPlayerRequest * request, Action_1_PlayFab_MultiplayerModels_ListMatchmakingTicketsForPlayerResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30840, void, ListMultiplayerServers, (ListMultiplayerServersRequest * request, Action_1_PlayFab_MultiplayerModels_ListMultiplayerServersResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30950, void, ListQosServers, (ListQosServersRequest * request, Action_1_PlayFab_MultiplayerModels_ListQosServersResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30A60, void, ListVirtualMachineSummaries, (ListVirtualMachineSummariesRequest * request, Action_1_PlayFab_MultiplayerModels_ListVirtualMachineSummariesResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30B70, void, RemoveMatchmakingQueue, (RemoveMatchmakingQueueRequest * request, Action_1_PlayFab_MultiplayerModels_RemoveMatchmakingQueueResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30C80, void, RequestMultiplayerServer, (RequestMultiplayerServerRequest * request, Action_1_PlayFab_MultiplayerModels_RequestMultiplayerServerResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30D90, void, RolloverContainerRegistryCredentials, (RolloverContainerRegistryCredentialsRequest * request, Action_1_PlayFab_MultiplayerModels_RolloverContainerRegistryCredentialsResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30EA0, void, SetMatchmakingQueue, (SetMatchmakingQueueRequest * request, Action_1_PlayFab_MultiplayerModels_SetMatchmakingQueueResult_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A30FB0, void, ShutdownMultiplayerServer, (ShutdownMultiplayerServerRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A310C0, void, UpdateBuildRegions, (UpdateBuildRegionsRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
IL2CPP_REGISTER_METHOD(0x01A311D0, void, UploadCertificate, (UploadCertificateRequest * request, Action_1_PlayFab_MultiplayerModels_EmptyResponse_ * resultCallback, Action_1_PlayFab_PlayFabError_ * errorCallback, Object * customData, Dictionary_2_System_String_System_String_ * extraHeaders));
}
