#include <interception_macros.h>

namespace app::methods::System::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1_ {
IL2CPP_REGISTER_METHOD(0x00611810, void, __ctor_1, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1_ * this_ptr, app::Object * object, app::void * method_1));
IL2CPP_REGISTER_METHOD(0x02B840F0, int32_t, Invoke_1, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1_ * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_System_Object_ x, app::UberShaderAnimatorStrategyStandard_Request_1_System_Object_ y));
IL2CPP_REGISTER_METHOD(0x02B8CD80, IAsyncResult *, BeginInvoke_1, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1_ * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_System_Object_ x, app::UberShaderAnimatorStrategyStandard_Request_1_System_Object_ y, app::AsyncCallback * callback, app::Object * object));
IL2CPP_REGISTER_METHOD(0x00F550D0, int32_t, EndInvoke_1, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1_ * this_ptr, app::IAsyncResult * result));
IL2CPP_REGISTER_METHOD(0x00611810, void, __ctor_2, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__1 * this_ptr, app::Object * object, app::void * method_1));
IL2CPP_REGISTER_METHOD(0x02B85630, int32_t, Invoke_2, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__1 * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_System_Single_ x, app::UberShaderAnimatorStrategyStandard_Request_1_System_Single_ y));
IL2CPP_REGISTER_METHOD(0x02B8CE70, IAsyncResult *, BeginInvoke_2, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__1 * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_System_Single_ x, app::UberShaderAnimatorStrategyStandard_Request_1_System_Single_ y, app::AsyncCallback * callback, app::Object * object));
IL2CPP_REGISTER_METHOD(0x00F550D0, int32_t, EndInvoke_2, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__1 * this_ptr, app::IAsyncResult * result));
IL2CPP_REGISTER_METHOD(0x00611810, void, __ctor_3, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__2 * this_ptr, app::Object * object, app::void * method_1));
IL2CPP_REGISTER_METHOD(0x02B866C0, int32_t, Invoke_3, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__2 * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Color_ x, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Color_ y));
IL2CPP_REGISTER_METHOD(0x02B8CF50, IAsyncResult *, BeginInvoke_3, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__2 * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Color_ x, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Color_ y, app::AsyncCallback * callback, app::Object * object));
IL2CPP_REGISTER_METHOD(0x00F550D0, int32_t, EndInvoke_3, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__2 * this_ptr, app::IAsyncResult * result));
IL2CPP_REGISTER_METHOD(0x00611810, void, __ctor_4, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__3 * this_ptr, app::Object * object, app::void * method_1));
IL2CPP_REGISTER_METHOD(0x02B866C0, int32_t, Invoke_4, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__3 * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Vector4_ x, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Vector4_ y));
IL2CPP_REGISTER_METHOD(0x02B8D040, IAsyncResult *, BeginInvoke_4, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__3 * this_ptr, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Vector4_ x, app::UberShaderAnimatorStrategyStandard_Request_1_UnityEngine_Vector4_ y, app::AsyncCallback * callback, app::Object * object));
IL2CPP_REGISTER_METHOD(0x00F550D0, int32_t, EndInvoke_4, (app::Comparison_1_Moon_Timeline_UberShaderAnimatorStrategyStandard_Request_1__3 * this_ptr, app::IAsyncResult * result));
}
