#include <interception_macros.h>

namespace app::methods::System::Data::ConstraintCollection {
IL2CPP_REGISTER_METHOD(0x0238DC10, void, __ctor, (ConstraintCollection * __this, DataTable * table));
IL2CPP_REGISTER_METHOD(0x002FB930, ArrayList *, get_List, (ConstraintCollection * __this));
IL2CPP_REGISTER_METHOD(0x0238DD90, Constraint_1 *, get_Item, (ConstraintCollection * __this, int32_t index));
IL2CPP_REGISTER_METHODINFO(0x04742590, ConstraintCollection_get_Item__MethodInfo);
IL2CPP_REGISTER_METHOD(0x002FA280, DataTable *, get_Table, (ConstraintCollection * __this));
IL2CPP_REGISTER_METHOD(0x0238DEB0, Constraint_1 *, get_Item, (ConstraintCollection * __this, String * name));
IL2CPP_REGISTER_METHODINFO(0x0471BBD0, ConstraintCollection_get_Item_1__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238DFC0, void, Add, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHOD(0x0238DFD0, void, Add, (ConstraintCollection * __this, Constraint_1 * constraint, bool addUniqueWhenAddingForeign));
IL2CPP_REGISTER_METHODINFO(0x04725A00, ConstraintCollection_Add_1__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238E7E0, Constraint_1 *, Add, (ConstraintCollection * __this, String * name, DataColumn__Array * columns, bool primaryKey));
IL2CPP_REGISTER_METHOD(0x0238E980, void, AddUniqueConstraint, (ConstraintCollection * __this, UniqueConstraint * constraint));
IL2CPP_REGISTER_METHODINFO(0x0472E030, ConstraintCollection_AddUniqueConstraint__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238EB00, void, AddForeignKeyConstraint, (ConstraintCollection * __this, ForeignKeyConstraint * constraint));
IL2CPP_REGISTER_METHODINFO(0x04753CE0, ConstraintCollection_AddForeignKeyConstraint__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238EBD0, bool, AutoGenerated, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHOD(0x0238ECF0, void, ArrayAdd, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHOD(0x0238ED30, void, ArrayRemove, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHOD(0x0238ED70, String *, AssignName, (ConstraintCollection * __this));
IL2CPP_REGISTER_METHOD(0x0238ED90, void, BaseAdd, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHODINFO(0x0477FF80, ConstraintCollection_BaseAdd__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238EEC0, void, BaseGroupSwitch, (ConstraintCollection * __this, Constraint_1__Array * oldArray, int32_t oldLength, Constraint_1__Array * newArray, int32_t newLength));
IL2CPP_REGISTER_METHOD(0x0238F140, void, BaseRemove, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHODINFO(0x047249D0, ConstraintCollection_BaseRemove__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238F500, bool, CanRemove, (ConstraintCollection * __this, Constraint_1 * constraint, bool fThrowException));
IL2CPP_REGISTER_METHOD(0x0238F530, void, Clear, (ConstraintCollection * __this));
IL2CPP_REGISTER_METHODINFO(0x0477BEC8, ConstraintCollection_Clear__MethodInfo);
IL2CPP_REGISTER_METHOD(0x0238FB90, bool, Contains, (ConstraintCollection * __this, String * name));
IL2CPP_REGISTER_METHOD(0x0238FBB0, bool, Contains, (ConstraintCollection * __this, String * name, bool caseSensitive));
IL2CPP_REGISTER_METHOD(0x0238FD40, Constraint_1 *, FindConstraint, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHOD(0x0238FF70, UniqueConstraint *, FindKeyConstraint, (ConstraintCollection * __this, DataColumn__Array * columns));
IL2CPP_REGISTER_METHOD(0x02390100, UniqueConstraint *, FindKeyConstraint, (ConstraintCollection * __this, DataColumn * column));
IL2CPP_REGISTER_METHOD(0x023902A0, ForeignKeyConstraint *, FindForeignKeyConstraint, (ConstraintCollection * __this, DataColumn__Array * parentColumns, DataColumn__Array * childColumns));
IL2CPP_REGISTER_METHOD(0x02390460, bool, CompareArrays, (DataColumn__Array * a1, DataColumn__Array * a2));
IL2CPP_REGISTER_METHOD(0x02390510, int32_t, InternalIndexOf, (ConstraintCollection * __this, String * constraintName));
IL2CPP_REGISTER_METHOD(0x023906D0, String *, MakeName, (ConstraintCollection * __this, int32_t index));
IL2CPP_REGISTER_METHOD(0x0194A3B0, void, OnCollectionChanged, (ConstraintCollection * __this, CollectionChangeEventArgs * ccevent));
IL2CPP_REGISTER_METHOD(0x023907A0, void, RegisterName, (ConstraintCollection * __this, String * name));
IL2CPP_REGISTER_METHODINFO(0x0470D9E0, ConstraintCollection_RegisterName__MethodInfo);
IL2CPP_REGISTER_METHOD(0x02390A60, void, Remove, (ConstraintCollection * __this, Constraint_1 * constraint));
IL2CPP_REGISTER_METHODINFO(0x04746C10, ConstraintCollection_Remove__MethodInfo);
IL2CPP_REGISTER_METHOD(0x02390D10, void, UnregisterName, (ConstraintCollection * __this, String * name));
IL2CPP_REGISTER_METHOD(0x02390DA0, void, FinishInitConstraints, (ConstraintCollection * __this));
IL2CPP_REGISTER_METHODINFO(0x04773060, ConstraintCollection_FinishInitConstraints__MethodInfo);
}
